Controllers/ActorsController.cs
using EticketsWebApp.Data;
using EticketsWebApp.Data.Base;
using EticketsWebApp.Data.Services;
using EticketsWebApp.Data.Static;
using EticketsWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EticketsWebApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
      
        public ActorsController(IActorsService service)
        {
            _service = service;
           
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var actors = await _service.GetAll();
            return View(actors);
        }

        // Create

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("profilePictureURL,FullName,Bio")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
           await _service.Add(actor);

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var ActorDetail =await _service.GetById(id);
            if (ActorDetail == null) return View("Empty"); 
            return View(ActorDetail);
        }

        // Edit action

        public async Task<IActionResult> Edit(int id)
        {
            var ActorDetail = await _service.GetById(id);
            if (ActorDetail == null) return View("NotFound");
            return View(ActorDetail);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.Updateasync(id, actor);

            return RedirectToAction(nameof(Index));
        }

        //Delete action

        public async Task<IActionResult> Delete(int id)
        {
            var ActorDetail = await _service.GetById(id);
            if (ActorDetail == null) return View("NotFound");
            return View(ActorDetail);
        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Actordetail = await _service.GetById(id);
            if (Actordetail == null) return View("NotFound");
            await _service.Delete(id);

            return RedirectToAction(nameof(Index));
        }


    }
}

Controllers/CinemasController.cs
using EticketsWebApp.Data;
using EticketsWebApp.Data.Services;
using EticketsWebApp.Data.Static;
using EticketsWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EticketsWebApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CinemasController : Controller
    {
        private readonly ICinemaService _service;

        public CinemasController(ICinemaService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var cinemas = await _service.GetAll();
            return View(cinemas);
        }

        [AllowAnonymous]
        //Cinema/Details
        public async Task<IActionResult> Details(int id)
        {
            var cinemaDetail = await _service.GetById(id);
            if (cinemaDetail == null) return View("NotFount");
            return View(cinemaDetail);
        }

        // Cinema/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")]Cinema cinema)
         {
            if (!ModelState.IsValid) return View(cinema);
            
            await _service.Add(cinema);
            return RedirectToAction(nameof(Index));
        }

        //Cinema/Edit

        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetail = await _service.GetById(id);
            if (cinemaDetail == null) return View("NotFount");
            return View(cinemaDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);
            if(id==cinema.Id) await _service.Updateasync(id,cinema);

            return View(cinema);
        }

        //Cinema/Delete

        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetail = await _service.GetById(id);
            if (cinemaDetail == null) return View("NotFount");
            return View(cinemaDetail);
        }

        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var cinemaDetail = await _service.GetById(id);
            if (cinemaDetail == null) return View("NotFount");
            await  _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/MoviesController.cs
using EticketsWebApp.Data;
using EticketsWebApp.Data.Services;
using EticketsWebApp.Data.Static;
using EticketsWebApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EticketsWebApp.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly IMovieService _service;

        public MoviesController(IMovieService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var movies = await _service.GetAll(n=>n.Cinema);
            return View(movies);
        }

        [AllowAnonymous]
        // Filter movies
        public async Task<IActionResult> Filter(string searchString)
        {
            var Allmovies = await _service.GetAll(n => n.Cinema);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filterdResult = Allmovies.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filterdResult);
            }
            return View("Index", Allmovies);
        }


        [AllowAnonymous]
        // Get: Movies/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieBYIdAsync(id);
            return View(movieDetail);
        }

        // Get: Movies/Create

        public async Task<IActionResult> Create()
        {
            var MovieDropdownData =await _service.GetNewMoviesDropdownsVlaues();

            ViewBag.actors = new SelectList(MovieDropdownData.Actors, "Id", "FullName");
            ViewBag.producers = new SelectList(MovieDropdownData.Producers, "Id", "FullName");
            ViewBag.cinemas = new SelectList(MovieDropdownData.Cinemas, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var MovieDropdownData = await _service.GetNewMoviesDropdownsVlaues();

                  ViewBag.actors = new SelectList(MovieDropdownData.Actors, "Id", "FullName");
                  ViewBag.producers = new SelectList(MovieDropdownData.Producers, "Id", "FullName");
                  ViewBag.cinemas = new SelectList(MovieDropdownData.Cinemas, "Id", "Name");
                  return View(movie);
            }
            await _service.CreateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
          
        }

        // Get: Movies/Edit/1

        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieBYIdAsync(id);
            if (movieDetails == null) return View("NotFound");

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                ImageUrl = movieDetails.ImageUrl,
                CinemaId = movieDetails.CinemaId,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                MovieCategory = movieDetails.MovieCategory,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.Id).ToList()
                
            };

            var MovieDropdownData = await _service.GetNewMoviesDropdownsVlaues();

            ViewBag.actors = new SelectList(MovieDropdownData.Actors, "Id", "FullName");
            ViewBag.producers = new SelectList(MovieDropdownData.Producers, "Id", "FullName");
            ViewBag.cinemas = new SelectList(MovieDropdownData.Cinemas, "Id", "Name");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,NewMovieVM movie)
        {
            if (id != movie.Id) return View("NotFound");


            if (!ModelState.IsValid)
            {
                var MovieDropdownData = await _service.GetNewMoviesDropdownsVlaues();

                ViewBag.actors = new SelectList(MovieDropdownData.Actors, "Id", "FullName");
                ViewBag.producers = new SelectList(MovieDropdownData.Producers, "Id", "FullName");
                ViewBag.cinemas = new SelectList(MovieDropdownData.Cinemas, "Id", "Name");
                return View(movie);
            }
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));

        }

    }
}

Controllers/OrdersController.cs
using EticketsWebApp.Data.Cart;
using EticketsWebApp.Data.Services;
using EticketsWebApp.Data.Static;
using EticketsWebApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EticketsWebApp.Controllers
{

    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;

        public OrdersController(IMovieService movieService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _movieService = movieService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        
        public  async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole =User.FindFirstValue(ClaimTypes.Role);

            var orders =await _orderService.GetOrderByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }
        
        public IActionResult ShoppingCart()
        {
            var Items = _shoppingCart.GetShoppingCartItem();
            _shoppingCart.ShoppingCarteItems = Items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                shoppingcartTotal = _shoppingCart.GetShoppingCartTotal()
            }; 
            return View(response);
        }
        
        public async Task<RedirectToActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _movieService.GetMovieBYIdAsync(id);

            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        
        public async Task<RedirectToActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _movieService.GetMovieBYIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItem();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.storeOrder(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");


        }
    }
}

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1>You've reached the end of the internet</h1>
    </div>
    <hr />
    <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home</a>
</div>

Views/Shared/_CreateItem.cshtml
@model string;
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position:fixed; right:25px; bottom:25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="fa-solid fa-plus"></i> New</a>
    </div>
}

Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (User.Identity.IsAuthenticated)
{
    @*User profile*@
    <div class="dropdown">
        <div class="btn-group">
            <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
            </button>
            <ul class="dropdown-menu" aria-labelledby="profile-btn">
                <li>
                    <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                        <i class="bi bi-collection"></i> Orders
                    </a>
                </li>
                @if (User.IsInRole("Admin"))
                {
                                 <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                            <i class="bg-dark bi bi-person"></i> Users
                    </a>
                </li>
                } 
            </ul>
        </div>
    </div>

    <span style="padding:5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-left"></i>  Log out
        </button>
    </form>
}
else
{
    <a class="nav-link text-white me-3" asp-controller="Account" asp-action="Login">
        <i class="bi bi-capslock"></i> Log in
    </a>
     <a class="nav-link text-white" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-lines-fill"></i> Register
     </a>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://kit.fontawesome.com/88c0fe7bb2.js" crossorigin="anonymous"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EticketsWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EticketsWebApp.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap/dist/css/bootswatch.min.css" rel="stylesheet" />
</head>
<body>
    <!--navbar-->
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Movies" asp-action="Index">eTickets</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Movies" asp-action="Index">
                            Movies
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
@*                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>*@
                    <li class="nav-item dropdown">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")){
                        <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown"  role="button" aria-haspopup="true" aria-expanded="false">Management</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="Cinemas"
                               asp-action="Index">Cinemas</a>
                            <a class="dropdown-item" asp-controller="Producers"
                               asp-action="Index">Producers</a>
                            <a class="dropdown-item" asp-controller="Actors"
                               asp-action="Index">Actors</a>
                        </div>
                        }
                    </li>
                </ul>
                <form class="d-flex" asp-controller="Movies" asp-action="Filter">
                    <input name="searchString" class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
                <ul>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                <partial name="_Identity.cshtml"></partial>
            </div>
        </div>
    </nav>
    <!--navbar-->
<span>
   @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">
                                <i class="bi bi-film"></i> Movies
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <!-- Example single danger button -->
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <div class="btn-group">
                                    <button type="button" class="btn btn-outline dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-gear"></i> Management
                                </button>
                                
                                     <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item"
                                           asp-controller="Cinemas"
                                           asp-action="Index">
                                            <i class="bi bi-camera-reels"></i>Cinemas
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-controller="Producers"
                                           asp-action="Index">
                                            <i class="bi bi-headset"></i> Producers
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item"
                                           asp-controller="Actors"
                                           asp-action="Index">
                                            <i class="bi bi-person-square"></i>  Actors
                                        </a>
                                    </li>
                                </ul>
                                
                               


                            </div>
                            }
                        </li>
                    </ul> 
                        <form class="form-inline my-2 my-lg-0 " asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                          <input name="searchString" type="text" class="form-control d-inline" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">         
                        </form>
                        <ul>
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        </ul>
                    <partial name="_Identity.cshtml"></partial>
                   
                </div>
            </div>
        </nav>
    </header>*@
    </span>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-facebook-f"></i>
                </a>

                <!-- Twitter -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-twitter"></i>
                </a>

                <!-- Google -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-google"></i>
                </a>

                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-instagram"></i>
                </a>

                <!-- Linkedin -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-linkedin-in"></i>
                </a>

                <!-- Github -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-github"></i>
                </a>
            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
  @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Etickets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>